import streamlit as st
from pathlib import Path

st.title("📋 Table of Contents")
st.caption((Path(__file__).parent.parent / "content" / "table_of_contents.md").read_text(encoding="utf-8").strip())
st.markdown("---")


def toc_row(path, label, icon, description):
    col_link, col_desc = st.columns([1.4, 2.6])
    with col_link:
        st.page_link(path, label=label, icon=icon)
    with col_desc:
        st.markdown(
            f'<p style="margin-top:5px;color:rgba(255,255,255,0.55);font-size:14px;">{description}</p>',
            unsafe_allow_html=True,
        )


# ── The Golden Cleat Awards ───────────────────────────────────────────────────
st.markdown("### ✨ The Golden Cleat Awards — Best Performances")
toc_row("pages/best_players.py",        "PPR Royalty",          "⭐", "The 4 highest point earners of the season ranked by total PPR score.")
toc_row("pages/team_carriers.py",       "Carrying the Load",    "🏈", "Players who made up the biggest share of their NFL team's total fantasy output.")
toc_row("pages/best_games.py",          "Ceiling Shatterers",   "🔥", "The 4 best individual weekly performances of the season by PPR score.")
toc_row("pages/no_td_needed.py",        "We Need TDs?",         "🚫", "The highest-scoring weeks of the season where the player found the end zone zero times.")
toc_row("pages/unexpected_booms.py",    "Lightning in a Bottle","💥", "The biggest single-game explosions, ranked by how far a player's best week exceeded their normal average.")
toc_row("pages/glow_ups.py",            "Late Bloomers",        "📈", "Players who improved the most from the first half (Weeks 1–8) to the second half (Weeks 9–17).")
toc_row("pages/league_winners.py",      "Set & Forget",         "🏆", "The most reliable weekly starters — high output and consistent, with a tunable penalty for volatility.")
toc_row("pages/playoff_winners.py",     "When It Matters Most", "🥇", "The best performers across fantasy playoff weeks 15–17, when every point counts.")
toc_row("pages/defense_vs_position.py", "Position Proof",       "🛡️", "The 4 stingiest defenses against each skill position, measured by total PPR allowed.")

st.markdown("---")

# ── The JaMarcus Awards ───────────────────────────────────────────────────────
st.markdown("### 💀 The JaMarcus Awards — Worst Performances")
toc_row("pages/worst_players.py",              "They Participated", "🔻", "The lowest total scorers among players who suited up for at least 16 games — full season, full disappointment.")
toc_row("pages/worst_games.py",                "Walk of Shame",     "🥶", "The 4 worst individual weekly performances of the season, among players who actually took the field.")
toc_row("pages/biggest_busts.py",              "You Had One Job",   "⬇️", "The most crushing single-game busts, ranked by how far a player fell below their own average.")
toc_row("pages/fall_offs.py",                  "Running on Empty",  "📉", "Players who fell off the hardest — biggest average points decline from the first half to the second half.")
toc_row("pages/defense_vs_position_worst.py",  "Position Sieve",    "🪣", "The 4 most generous defenses against each skill position — the ones fantasy managers loved to exploit.")

st.markdown("---")

# ── My Fantasy Story ─────────────────────────────────────────────────────────
st.markdown("### 📖 My Fantasy Story")
toc_row("pages/my_fantasy_story.py", "My Fantasy Story", "📖", "The full arc — from a 2–5 draft disaster to a 2nd place finish.")

st.markdown("---")

# ── General ───────────────────────────────────────────────────────────────────
st.markdown("### 🗂️ General")
toc_row("pages/player_lookup.py",       "Player Lookup",   "🔍", "Search any player and view their week-by-week PPR bar chart with an average line.")
toc_row("pages/player_comparison.py",   "Compare Players", "⚖️", "Place two players side by side in a butterfly envelope chart to compare their scoring arcs across all 17 weeks.")
toc_row("pages/team_fantasy_points.py", "Team Scores",     "🏟️", "Total PPR points generated by every NFL team, broken down by position — in division view or ranked order.")
